on: 
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  workflow_call:
    inputs:
      username:
        type: string
        description: "input user name"
        required: true
        default: deere123456
        
    # secrets:
    #   token:
    #     required: true                             
jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: run a Hello Script
        run: echo Hello, ${{ inputs.username }}
        
  production:
    runs-on: ubuntu-latest
    needs: staging
    steps:
      - name: run a Hello Script
        run: echo Hello, ${{ inputs.username }}